destination: pdf
permalink: none
markdown: kramdown
exclude:
  - bin
  - README.md
  - Gemfile
  - Gemfile.lock

kramdown:
  input: 'GFM'
  hard_wrap: false
  syntax_highlighter_opts:
    line_numbers: :inline
